name: Docker

on:
  workflow_dispatch:
  create:
  push:
  pull_request:

jobs:
  # Naming -------------------------------------------------------
  name:
    runs-on: ubuntu-latest
    name: Name
    outputs:
      name: ${{ steps.name.outputs.name }}
    
    steps:
    - name: Create image name
      id: name
      run: |
        ORIGINAL_NAME=${{ github.repository }}
        CLEAN_NAME=$(echo "$ORIGINAL_NAME" | sed 's/^[^/]*\///' | tr './' '--' | awk '{print tolower($0)}')
        echo "::notice::Docker image name is $CLEAN_NAME"
        echo "name=$CLEAN_NAME" >> "$GITHUB_OUTPUT"

  # Push --------------------------------------------------------
  push:
    runs-on: ubuntu-latest
    name: Push
    needs: [name]
    strategy:
      fail-fast: true
      matrix:
        arch:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set push flag
        id: set-push-flag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "PUSH_FLAG=true" >> $GITHUB_ENV
          else
            echo "PUSH_FLAG=false" >> $GITHUB_ENV

      - name: Push
        uses: netwatching/action.docker.push@v2.1.0
        with:
          name: ${{ needs.name.outputs.name }}
          arch: ${{ matrix.arch }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ env.PUSH_FLAG }}

  # Merge --------------------------------------------------------
  merge:
    runs-on: ubuntu-latest
    if: env.PUSH_FLAG == 'true'
    name: Merge
    needs: [name, push]
    steps:
      - name: Merge
        uses: netwatching/action.docker.merge@v1.1.8
        with:
          name: ${{ needs.name.outputs.name }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          