name: Commitlint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: |
          npm install -g @commitlint/config-conventional @commitlint/cli

      - name: Check commit count
        id: commit-count
        run: echo "::set-output name=count::$(git rev-list --count HEAD)"

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push' && steps.commit-count.outputs.count != '1'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate only commit in repo with commitlint
        if: github.event_name == 'push' && steps.commit-count.outputs.count == '1'
        run: npx commitlint --from HEAD --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
