name: Commitlint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: |
          npm install -g @commitlint/config-conventional @commitlint/cli

      - name: Check commit count
        id: commit-count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Validate commits with commitlint
        if: github.event_name == 'push'
        run: |
          if [ ${{ env.COMMIT_COUNT }} -gt 1 ]; then
            npx commitlint --from HEAD~1 --to HEAD --verbose
          else
            echo "Only one commit present, skipping commitlint for range HEAD~1..HEAD"
          fi

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
